import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Home Page","description":"","frontmatter":{"prev":{"text":"Menu Buttons","link":"/guide/widgets/settings/menu"},"next":{"text":"Main Page","link":"/guide/widgets/home/main"}},"headers":[],"relativePath":"guide/widgets/home/index.md","filePath":"guide/widgets/home/index.md","lastUpdated":1775413032000}');
const _sfc_main = { name: "guide/widgets/home/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="home-page" tabindex="-1">Home Page <a class="header-anchor" href="#home-page" aria-label="Permalink to &quot;Home Page&quot;">​</a></h1><p>The home page <code>home.yaml</code> includes two separate files to separate functionality and improve code structure. Essentially, it&#39;s just a consolidation file.</p><h2 id="architecture-overview" tabindex="-1">Architecture Overview <a class="header-anchor" href="#architecture-overview" aria-label="Permalink to &quot;Architecture Overview&quot;">​</a></h2><h3 id="package-structure" tabindex="-1"><strong>Package Structure:</strong> <a class="header-anchor" href="#package-structure" aria-label="Permalink to &quot;**Package Structure:**&quot;">​</a></h3><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">packages</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  home</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">!include</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> home_widget.yaml</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  info</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">!include</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> info_page.yaml</span></span></code></pre></div><p>The home page consists of two main modules:</p><ul><li><strong><code>home_widget.yaml</code></strong> - Main page</li><li><strong><code>info_page.yaml</code></strong> - Device information data</li></ul><h2 id="modular-system" tabindex="-1">Modular System <a class="header-anchor" href="#modular-system" aria-label="Permalink to &quot;Modular System&quot;">​</a></h2><h3 id="separation-of-concerns" tabindex="-1"><strong>Separation of Concerns</strong> <a class="header-anchor" href="#separation-of-concerns" aria-label="Permalink to &quot;**Separation of Concerns**&quot;">​</a></h3><ul><li>Each file is responsible for specific functionality</li><li>Logical separation of widget and information block</li><li>Simplified code navigation</li></ul><h3 id="maintainability" tabindex="-1"><strong>Maintainability</strong> <a class="header-anchor" href="#maintainability" aria-label="Permalink to &quot;**Maintainability**&quot;">​</a></h3><ul><li>Changes in one module don&#39;t affect others</li><li>Easier to find and fix issues</li><li>Independent module development</li></ul><h3 id="code-reusability" tabindex="-1"><strong>Code Reusability</strong> <a class="header-anchor" href="#code-reusability" aria-label="Permalink to &quot;**Code Reusability**&quot;">​</a></h3><ul><li>Modules can be used in other projects</li><li>Component standardization</li></ul><h3 id="scalability" tabindex="-1"><strong>Scalability</strong> <a class="header-anchor" href="#scalability" aria-label="Permalink to &quot;**Scalability**&quot;">​</a></h3><ul><li>Easy to add new modules</li><li>Flexible architecture</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("guide/widgets/home/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
