import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Конфигурация цветов в ESPHome","description":"","frontmatter":{},"headers":[],"relativePath":"ru/guide/configuration/colors.md","filePath":"ru/guide/configuration/colors.md","lastUpdated":1775413032000}');
const _sfc_main = { name: "ru/guide/configuration/colors.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="конфигурация-цветов-в-esphome" tabindex="-1">Конфигурация цветов в ESPHome <a class="header-anchor" href="#конфигурация-цветов-в-esphome" aria-label="Permalink to &quot;Конфигурация цветов в ESPHome&quot;">​</a></h1><p>Цветовая схема — основа визуального дизайна интерфейса. В ESPHome цвета определяются централизованно для единообразия и удобства изменения темы оформления.</p><p>В этом проекте используется отдельный файл <code>colors.yaml</code>, который подключается в <code>main.yaml</code></p><h2 id="структура-конфигурации-цвета" tabindex="-1">Структура конфигурации цвета <a class="header-anchor" href="#структура-конфигурации-цвета" aria-label="Permalink to &quot;Структура конфигурации цвета&quot;">​</a></h2><h3 id="базовыи-формат" tabindex="-1">Базовый формат <a class="header-anchor" href="#базовыи-формат" aria-label="Permalink to &quot;Базовый формат&quot;">​</a></h3><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">- </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">id</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">color_sky_blue</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  hex</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">3FA7F3</span></span></code></pre></div><h3 id="параметры" tabindex="-1">Параметры <a class="header-anchor" href="#параметры" aria-label="Permalink to &quot;Параметры&quot;">​</a></h3><h4 id="id" tabindex="-1"><code>id</code> <a class="header-anchor" href="#id" aria-label="Permalink to &quot;\`id\`&quot;">​</a></h4><p><strong>Назначение</strong>: Уникальный идентификатор цвета</p><ul><li>Используется для ссылки в LVGL виджетах</li><li>Рекомендуется описательное имя</li><li>Формат: <code>color_название_цвета</code></li></ul><h4 id="hex" tabindex="-1"><code>hex</code> <a class="header-anchor" href="#hex" aria-label="Permalink to &quot;\`hex\`&quot;">​</a></h4><p><strong>Назначение</strong>: Шестнадцатеричный код цвета</p><ul><li>Формат: <code>RRGGBB</code> (без символа #)</li><li>Диапазон: <code>000000</code> (черный) до <code>FFFFFF</code> (белый)</li><li>Пример: <code>3FA7F3</code> = RGB(63, 167, 243)</li></ul><h2 id="практическое-использование" tabindex="-1">Практическое использование <a class="header-anchor" href="#практическое-использование" aria-label="Permalink to &quot;Практическое использование&quot;">​</a></h2><h3 id="в-lvgl-виджетах" tabindex="-1">В LVGL виджетах <a class="header-anchor" href="#в-lvgl-виджетах" aria-label="Permalink to &quot;В LVGL виджетах&quot;">​</a></h3><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Кнопка</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">- </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">button</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    bg_color</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">color_sky_blue</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    border_color</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">color_blue</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    shadow_color</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">color_black</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Текст</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">- </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">label</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    text_color</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">color_white</span></span>
<span class="line"></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Дуга</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">- </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">arc</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    arc_color</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">color_dark_gray</span></span></code></pre></div><h3 id="адаптивные-цвета" tabindex="-1">Адаптивные цвета <a class="header-anchor" href="#адаптивные-цвета" aria-label="Permalink to &quot;Адаптивные цвета&quot;">​</a></h3><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#6A737D", "--shiki-dark": "#6A737D" })}"># Цвет в зависимости от состояния</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">switch</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">  - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">platform</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">template</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    turn_on_action</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">      - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">lvgl.label.update</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">          id</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">my_status</span></span>
<span class="line highlighted"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">          text_color</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">color_green</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">    turn_off_action</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">      - </span><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">lvgl.label.update</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">          id</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">my_status</span></span>
<span class="line highlighted"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">          text_color</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}">color_steel_blue</span></span></code></pre></div><h2 id="оптимизация-для-дисплея" tabindex="-1">Оптимизация для дисплея <a class="header-anchor" href="#оптимизация-для-дисплея" aria-label="Permalink to &quot;Оптимизация для дисплея&quot;">​</a></h2><h3 id="_16-битная-глубина-цвета" tabindex="-1">16-битная глубина цвета <a class="header-anchor" href="#_16-битная-глубина-цвета" aria-label="Permalink to &quot;16-битная глубина цвета&quot;">​</a></h3><p>При <code>color_depth: 16</code> цвета автоматически конвертируются в RGB565:</p><ul><li>Красный: 5 бит (32 оттенка)</li><li>Зеленый: 6 бит (64 оттенка)</li><li>Синий: 5 бит (32 оттенка)</li></ul><h3 id="рекомендации" tabindex="-1">Рекомендации <a class="header-anchor" href="#рекомендации" aria-label="Permalink to &quot;Рекомендации&quot;">​</a></h3><ul><li>Избегайте слишком тонких градаций</li><li>Тестируйте цвета на реальном дисплее</li><li>Учитывайте особенности LCD панели</li></ul><h2 id="заключение" tabindex="-1">Заключение <a class="header-anchor" href="#заключение" aria-label="Permalink to &quot;Заключение&quot;">​</a></h2><p>Продуманная цветовая схема обеспечивает:</p><ul><li><strong>Читаемость</strong> — достаточный контраст для всех элементов</li><li><strong>Интуитивность</strong> — семантически правильные цвета</li><li><strong>Единообразие</strong> — централизованное управление палитрой</li><li><strong>Эстетику</strong> — гармоничное сочетание оттенков</li></ul><p>Используйте предложенную палитру как основу и адаптируйте под свои потребности, сохраняя принципы контрастности и семантической корректности.</p></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("ru/guide/configuration/colors.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const colors = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  colors as default
};
