import { ssrRenderAttrs, ssrRenderStyle } from "vue/server-renderer";
import { useSSRContext } from "vue";
import { _ as _export_sfc } from "./plugin-vue_export-helper.1tPrXgE0.js";
const __pageData = JSON.parse('{"title":"Домашняя страница","description":"","frontmatter":{"prev":{"text":"Кнопки меню","link":"/ru/guide/widgets/home"},"next":{"text":"Главная страница","link":"/ru/guide/widgets/home/main"}},"headers":[],"relativePath":"ru/guide/widgets/home/index.md","filePath":"ru/guide/widgets/home/index.md","lastUpdated":1775413032000}');
const _sfc_main = { name: "ru/guide/widgets/home/index.md" };
function _sfc_ssrRender(_ctx, _push, _parent, _attrs, $props, $setup, $data, $options) {
  _push(`<div${ssrRenderAttrs(_attrs)}><h1 id="домашняя-страница" tabindex="-1">Домашняя страница <a class="header-anchor" href="#домашняя-страница" aria-label="Permalink to &quot;Домашняя страница&quot;">​</a></h1><p>Домашняя страница <code>home.yaml</code> подключает два отдельных файла для разделения функциональности и улучшения структуры кода. По большому счету это просто объединительный файл.</p><h2 id="обзор-архитектуры" tabindex="-1">Обзор архитектуры <a class="header-anchor" href="#обзор-архитектуры" aria-label="Permalink to &quot;Обзор архитектуры&quot;">​</a></h2><h3 id="структура-пакетов" tabindex="-1"><strong>Структура пакетов:</strong> <a class="header-anchor" href="#структура-пакетов" aria-label="Permalink to &quot;**Структура пакетов:**&quot;">​</a></h3><div class="language-yaml vp-adaptive-theme"><button title="Copy Code" class="copy"></button><span class="lang">yaml</span><pre class="shiki shiki-themes github-light github-dark vp-code" tabindex="0"><code><span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">packages</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">:</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  home</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">!include</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> home_widget.yaml</span></span>
<span class="line"><span style="${ssrRenderStyle({ "--shiki-light": "#22863A", "--shiki-dark": "#85E89D" })}">  info</span><span style="${ssrRenderStyle({ "--shiki-light": "#24292E", "--shiki-dark": "#E1E4E8" })}">: </span><span style="${ssrRenderStyle({ "--shiki-light": "#D73A49", "--shiki-dark": "#F97583" })}">!include</span><span style="${ssrRenderStyle({ "--shiki-light": "#032F62", "--shiki-dark": "#9ECBFF" })}"> info_page.yaml</span></span></code></pre></div><p>Домашняя страница состоит из двух основных модулей:</p><ul><li><strong><code>home_widget.yaml</code></strong> - Главная страница</li><li><strong><code>info_page.yaml</code></strong> - Информационные данные устройства</li></ul><h2 id="модульная-система" tabindex="-1">Модульная система <a class="header-anchor" href="#модульная-система" aria-label="Permalink to &quot;Модульная система&quot;">​</a></h2><h3 id="разделение-ответственности" tabindex="-1"><strong>Разделение ответственности</strong> <a class="header-anchor" href="#разделение-ответственности" aria-label="Permalink to &quot;**Разделение ответственности**&quot;">​</a></h3><ul><li>Каждый файл отвечает за определенную функциональность</li><li>Логическое разделение виджета и информационного блока</li><li>Упрощение навигации по коду</li></ul><h3 id="удобство-сопровождения" tabindex="-1"><strong>Удобство сопровождения</strong> <a class="header-anchor" href="#удобство-сопровождения" aria-label="Permalink to &quot;**Удобство сопровождения**&quot;">​</a></h3><ul><li>Изменения в одном модуле не затрагивают другие</li><li>Легче найти и исправить проблемы</li><li>Независимая разработка модулей</li></ul><h3 id="переиспользование-кода" tabindex="-1"><strong>Переиспользование кода</strong> <a class="header-anchor" href="#переиспользование-кода" aria-label="Permalink to &quot;**Переиспользование кода**&quot;">​</a></h3><ul><li>Модули можно использовать в других проектах</li><li>Стандартизация компонентов</li></ul><h3 id="масштабируемость" tabindex="-1"><strong>Масштабируемость</strong> <a class="header-anchor" href="#масштабируемость" aria-label="Permalink to &quot;**Масштабируемость**&quot;">​</a></h3><ul><li>Легко добавлять новые модули</li><li>Гибкая архитектура</li></ul></div>`);
}
const _sfc_setup = _sfc_main.setup;
_sfc_main.setup = (props, ctx) => {
  const ssrContext = useSSRContext();
  (ssrContext.modules || (ssrContext.modules = /* @__PURE__ */ new Set())).add("ru/guide/widgets/home/index.md");
  return _sfc_setup ? _sfc_setup(props, ctx) : void 0;
};
const index = /* @__PURE__ */ _export_sfc(_sfc_main, [["ssrRender", _sfc_ssrRender]]);
export {
  __pageData,
  index as default
};
